# Generated by Django 5.0.7 on 2024-08-21 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="botthread",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="botthread",
            name="chat_content",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="botthread",
            name="questions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="botthread",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
