# Generated by Django 5.0.7 on 2024-08-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_botthread_chat_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotThreadContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_content", models.JSONField()),
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_content",
                        to="api.botthread",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ThreadContent",
        ),
    ]
