# Generated by Django 5.0.7 on 2024-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_botthreadcontent_delete_threadcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botthreadcontent",
            name="chat_content",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="UserThread",
        ),
    ]
