# Generated by Django 5.0.7 on 2024-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_botthreadcontent_chat_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botthreadcontent",
            name="chat_content",
            field=models.JSONField(default=dict),
        ),
    ]
