# Generated by Django 5.0.7 on 2024-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_botthreadcontent_chat_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botthreadcontent",
            name="chat_content",
            field=models.JSONField(default=list),
        ),
    ]
