# Generated by Django 5.0.7 on 2024-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_botthreadcontent_chat_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="botthreadcontent",
            name="form_content",
            field=models.JSONField(null=True),
        ),
    ]
