# Generated by Django 5.0.7 on 2024-09-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_botthreadcontent_form_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_title", models.CharField(blank=True, max_length=255)),
                (
                    "bot_thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="api.botthread",
                    ),
                ),
            ],
        ),
    ]
