# Generated by Django 5.0.7 on 2024-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="forms",
            name="shared_form",
            field=models.JSONField(default=dict),
        ),
    ]
